api_version: v1

upstreams:
  - id: mock-service
    endpoints:
      - id: mock-1
        url: http://127.0.0.1:18080
        weight: 100

routes:
  - id: hello
    method: GET
    path: /hello
    upstream: mock-service

policies:
  request_timeout: 3s
  rate: 0
  burst: 0